# Generated by Django 4.1.8 on 2023-04-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
